name: Rebase studentbranches with main

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    paths:
    - 'src/lecture/**'
    - 'src/excersises/**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rebase-main-to-studentbranches:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        studentbranch: [ 's21' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - uses: tiacsys/git-rebase@v1.0.1 # https://github.com/marketplace/actions/git-rebase-action
      with:
        repo: "https://matthiasbergneels:${{ secrets.GITHUB_TOKEN }}@github.com/matthiasbergneels/dhbwmawwi2022seb.git"
        source_branch: main
        destination_branch: ${{ matrix.studentbranch }} 
