name: Rebase studentbranches with main

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    paths:
    - 'src/lecture/**'
    - 'src/excersises/**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rebase-main-to-studentbranches:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        studentbranch: [ 's21' ]
    steps:
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Rebase main to student branches
      run: |
          git clone https://github.com/matthiasbergneels/dhbwmawwi2022seb.git /root/repo --origin remote-repo && cd /root/repo
          git fetch remote-repo '+refs/heads/*:refs/heads/*' --update-head-ok
          git --no-pager branch -a -vv
          git rebase --onto main main ${{ matrix.studentbranch }}
          git checkout ${{ matrix.studentbranch }}
          git status
          
          
