name: Rebase studentbranches with main

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    paths:
    - 'src/lecture/**'
    - 'src/excersises/**'
    
jobs:
  rebase-main-to-studentbranches:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        studentbranch: [ 's21' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Rebase main to student branches
      run: |
          git fetch
          git checkout main
          git pull
          git checkout ${{ matrix.studentbranch }}
          git rebase main
          git push
