name: Rebase studentbranches with main

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    paths:
      - 'src/lecture/**'
      - 'src/excersises/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rebase-main-to-studentbranches:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        studentbranch: [ 's01', 's02', 's03', 's04', 's05', 's06', 's07', 's08', 's09', 's10', 's11', 's12', 's13', 's14', 's15', 's16', 's17', 's18', 's19', 's20', 's21' ]
    steps:
      - name: Rebase main to student branches
        uses: tiacsys/git-rebase@v1.0.1
        with:
          repo: "matthiasbergneels/dhbwmawwi2022seb"
          source_branch: ${{ matrix.studentbranch }}
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
