name: Rebase studentbranches with main

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    paths:
    - 'src/lecture/**'
    - 'src/excersises/**' # spelling mistake - exercises
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  rebase-main-to-studentbranches:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        studentbranch: [ 's21' ]
    steps:
    - uses: tiacsys/git-rebase@v1.0.1 # https://github.com/marketplace/actions/git-rebase-action
      with:
        repo: "matthiasbergneels/dhbwmawwi2022seb"
        source_branch: main
        destination_branch: ${{ matrix.studentbranch }} 
